version: "3.8"

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=uxmcp
      - MCP_SERVER_URL=http://api:8000/mcp
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=uxmcp
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: